### ISSUE TITLE
Tealium SDK breaks LiveEdit in Android Studio

### ISSUE THREAD

**Issue by ChristianSteffensen** [Tealium/tealium-kotlin#211] opened 2023-04-24 13:03 UTC
Hi, it seems that adding the Tealium SDK breaks the Live Edit functionality in Android Studio. This bug happens as soon as 
`implementation 'com.tealium:kotlin-core:1.5.2'` 
is added to the build.gradle file.

I'm not sure exactly what the error is here, but since it only happens for this single dependency, I'm guessing it's a bug on your side. 

We're using minSDK 26, but I've tried changing it to 21 and that didn't help.

Android Studio Giraffe Beta 1
Kotlin 1.8.20
AGP 8.1.0-beta01 (Happens on 7.4.2 too)
Gradle 8.0

![image](https://user-images.githubusercontent.com/6247508/234002500-e39075e6-fa9a-41f6-8f5b-49c30c4964fb.png)

**Comment by craigrouse** [comment] 2023-04-24 14:19
@ChristianSteffensen We'll take a look at this ASAP. In the meantime, we noticed you're using a beta version of both Android Studio and the Android Gradle Plugin - have you been able to try with the latest stable Android Studio to see if the issue exists there too?

**Comment by jameskeith** [comment] 2023-04-24 15:16
@ChristianSteffensen - In extension to what @craigrouse has added. I've just launched a Compose project using Arctic Fox and had a couple of different LiveEdit render issues. The latter of which was resolved by updating to the latest Stable version of Android Studio Flamingo (AGP v7.4.2,  Kotlin 1.8.10) .
Everything works okay for me now, so I suspect there's a good chance that this is an issue with Android Studio version more than anything else.

https://stackoverflow.com/questions/75937541/jetpack-compose-preview-render-problem-with-java-lang-classnotfoundexception-an
https://stackoverflow.com/questions/68845898/jetpack-compose-preview-stopped-working-in-arctic-fox-with-patch-1

**Comment by jameskeith** [comment] 2023-04-25 13:20
@ChristianSteffensen 
Thanks for the feedback. I've installed the Giraffe beta on another device and updated through to AGP/Gradle v8.0 to test that also; but I'm still unable to reproduce that error - Live Edits still work for me.

I appreciate that it's a little odd that it only seems to affect our dependency on your machine, but there's a limited number of ways for us to set the `minApi` when building and I don't believe we are doing anything out of the ordinary.
Since this only seems to affect the Beta release of Android Studio I'd suggest raising it with Google/JetBrains and/or waiting until it's received additional patches as there are already some issues raised with Giraffe relating to LiveEdit
https://issuetracker.google.com/issues/274165708

**Comment by ChristianSteffensen** [comment] 2023-04-25 13:39
@jameskeith That's interesting, I can reproduce it on multiple machines with the template Compose project. 

But thanks for looking into it. I'll cross my fingers that it will be resolved with future AS patches :)

**Closed** 2024-05-08 11:03 UTC
